@url = http://localhost:5000/employees

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDIiLCJ1bmlxdWVfbmFtZSI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMiIsImp0aSI6IjkwNzQzYWNiLTMxMTgtNGU1MS1iOTRkLWRjY2ZjNzE2ODdmMCIsImlhdCI6IjE2MDYyNDg5MjMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZW5hbnRPd25lciIsInRlbmFudElkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwiZmlyc3ROYW1lIjoiQWRhbSIsImxhc3ROYW1lIjoiTm93YWsiLCJuYmYiOjE2MDYyNDg5MjMsImV4cCI6MTYwNjMzODkyMywiaXNzIjoiaUhSUyJ9.8kLT7GWXwiRnesRsJa9ENPWu8YorUnLkZfaDRNG4H1E

###
GET {{url}}/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

