@url = http://localhost:5000/hotels/{{hotelId}}/rooms
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MDNmMGI5Ny01M2QyLTQyNWQtYTM3ZC1hMjFmNDMwYzE3M2YiLCJ1bmlxdWVfbmFtZSI6IjkwM2YwYjk3LTUzZDItNDI1ZC1hMzdkLWEyMWY0MzBjMTczZiIsImp0aSI6IjM3NmZlNWIzLWQ1ODQtNDBkZS1hZWNjLTVjMDY2YjUxZGFkZCIsImlhdCI6IjE2MDA4ODAzMzIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwibmJmIjoxNjAwODgwMzMyLCJleHAiOjE2MDA5NzAzMzIsImlzcyI6ImlIUlMifQ.31Vz6HqWvelSxIQV0T6GpPjFUkbDntxwsRVORQ1YboM
@hotelId = 98D8D799-6644-46D4-A211-71BEAE0E7B4F
@roomId = E20E198C-CCB4-4092-94E9-053A00A1F0F8


###
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{  
    "roomNumber" : "00001"
}

###
POST {{url}}/{{roomId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{  
    "startDate" : "2020-12-27",
    "endDate" : "2020-12-28",
    "numberOfPersons" : 2,
    "customerFirstName" : "Harry",
    "customerLastName" : "Potter",
    "customerEmailAddress" : "harry.potter@example.com",
    "customerPhoneNumber" : "+48123456789"
}




