@url = http://localhost:5000/hotels
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MDNmMGI5Ny01M2QyLTQyNWQtYTM3ZC1hMjFmNDMwYzE3M2YiLCJ1bmlxdWVfbmFtZSI6IjkwM2YwYjk3LTUzZDItNDI1ZC1hMzdkLWEyMWY0MzBjMTczZiIsImp0aSI6IjM3NmZlNWIzLWQ1ODQtNDBkZS1hZWNjLTVjMDY2YjUxZGFkZCIsImlhdCI6IjE2MDA4ODAzMzIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwibmJmIjoxNjAwODgwMzMyLCJleHAiOjE2MDA5NzAzMzIsImlzcyI6ImlIUlMifQ.31Vz6HqWvelSxIQV0T6GpPjFUkbDntxwsRVORQ1YboM
@hotelId = 7D36FF1D-9EBE-4A14-852D-8E7A8EB91586


###
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name" : "My first hotel !"
}

###
DELETE  {{url}}/{{hotelId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
POST {{url}}/{{hotelId}}/messageTemplates
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "message" : "My first hotel !",
  "messageType": 2,
  "communicationMethod": 1
}

###
GET {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}