@url = http://localhost:5000/hotels/{{hotelId}}/rooms
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYjdkYWZkNS04OTE0LTRlNWYtOThkNS1kZmFmYmQ0ZTI5MmQiLCJ1bmlxdWVfbmFtZSI6ImZiN2RhZmQ1LTg5MTQtNGU1Zi05OGQ1LWRmYWZiZDRlMjkyZCIsImp0aSI6IjJiYmZlY2U0LTk4YjMtNDZkOC04Yzk1LWNjMTk4MTA4MWExNSIsImlhdCI6IjE2MDA1MTkxNjUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwibmJmIjoxNjAwNTE5MTY1LCJleHAiOjE2MDA2MDkxNjUsImlzcyI6ImlIUlMifQ.GDBK8eaWuCL5h9YfcG6GZoCEOx_wiuExxOJq1wJjwj8
@hotelId = f1e349dc-04fa-458e-bf17-0599d4e4fa69
@roomId = 9bfc0f47-82de-447f-b37d-301147357179


###
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{  
    "roomNumber" : "My first room 1233!"
}

###
POST {{url}}/{{roomId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{  
    "startDate" : "2020-12-25",
    "endDate" : "2020-12-26",
    "numberOfPersons" : 2,
    "customerFirstName" : "Harry",
    "customerLastName" : "Potter",
    "customerEmailAddress" : "harry.potter@example.com",
    "customerPhoneNumber" : "+48123456789"
}

